OnBoarding: Authentication Flow
Rajan-p-simform/SimformGitExcercise pull request #2
Opened 2024-04-10 13:26 UTC by Rajan-p-simform

- Login Screen
- Register Screen
- Forget Password Screen

2024-04-11 12:15 UTC, nishchal-v requested changes
Formate the files properly with lines where required and remove extra lines

2024-04-11 12:15 UTC, nishchal-v commented on app/src/main/java/simform/gitexcercise/authentication/ForgetPasswordFragment.kt
> +
Remove the empty line here

2024-04-11 12:15 UTC, nishchal-v commented on app/src/main/java/simform/gitexcercise/authentication/LoginFragment.kt
> +
Same here as above comment

2024-04-11 12:15 UTC, nishchal-v commented on app/src/main/java/simform/gitexcercise/authentication/RegistrationFragment.kt
> +    override fun onCreateView(
Add a empty line above

2024-04-11 12:15 UTC, nishchal-v commented on app/src/main/java/simform/gitexcercise/authentication/LoginFragment.kt
> +            Navigation.findNavController(view).navigate(R.id.action_loginFragment_to_registrationFragment)
We can have a lazy variable of this navigation contorller

2024-04-11 12:15 UTC, nishchal-v commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Remove this demo code

2024-04-12 05:13 UTC, Rajan-p-simform commented
> * Formate the files properly with lines where required and remove extra lines
> * Change the title and the commit message as per our standards

2024-04-15 11:29 UTC, nishchal-v approved these changes

2024-04-15 11:30 UTC, merged